README.md
lean/expressions.lean
lean/metam.lean

A few examples for constructing expressions with some description of the functions used. These include both direct constructions and smart constructions.

Examples for contructing expressions

---

README.md
lean/intro.lean

Add an arithmetic DSL as an introduction.

add intro to DSLs

---

lean/monad-stacks.lean
md/monad-stacks.md

I left a few TODOs but the general concept is definitely captured I think.

feat: monad stacks

---

lean/main/tactics.lean
md/main/tactics.md

We explain basic use cases of `TacticM`, how to
access common data like goals, hypotheses, and how to
implement `sorry` and `trivial`.

Add initial tutorial on tactics.

---

lean/main/tactics.lean
md/main/tactics.md

@arthurpaulino I don't have many ideas for how to use macros for tactics. If you do, I'd be happy to add them.

[WIP] Add macro based tactics.

---

lean/main/macros.lean
lean/main/metam.lean
lean/main/syntax.lean
md/main/macros.md
md/main/metam.md
md/main/syntax.md

I left questions on sentences that I could not resolve.

chore(several files): some typos and some questions

---

lean/main/metam.lean

This PR adds a computation section to the `MetaM` chapter. It builds on PR #33.
I think the section as currently written doesn't mesh very well with the rest of
the chapter. It goes into considerably more detail and is less example-based.
How do we deal with this?
My preference would be to expand the rest of the chapter in similar fashion
since I think there is much more that needs to be said about `MetaM` operations
to make people effective metaprogrammers. This may necessitate splitting the
chapter at some point since it's going to get quite big. I can do this
expansion, but probably slowly since I can't devote too much time to this task.

metam: add intro; add computation section

---

README.md
lean/main/tactics.lean
md/main/tactics.md

addressing Sebastian's comments

---

lean/main/metam.lean
md/main/metam.md

It appears that the github workflow does not update markdown, so the blank lines of the last pull request had no effect. Hence a fresh one with manual editing.

manual new line in markdown

---

lean/main/macros.lean
md/main/macros.md

Addresses the syntax related parts from #47

feat: more on syntax quotations and hygiene

---

lean/main/metam.lean

remove unused parameter from whnf'

---

lean/main/tactics.lean
md/main/tactics.md

I extracted here one of the questions from #79, to group together similar looking one.

lint(lean/main/tactics): remove unused definition

---

lean/main/tactics.lean
md/main/tactics.md

A few changes that I think may be desirable, but I am not completely sure.  Each element of the diff should be interpreted as a question, whether the change is better or worse than the original!

questions(lean/main/tactics.lean)

---

lean/main/expressions.lean
md/main/expressions.md

As discussed here:
https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/Bvars

expressions: clarify bvar/fvar terminology

---

lean/extra/pretty-printing.lean
md/extra/pretty-printing.md

Quick fixes for pdf lists to render fine

---

lean/main/intro.lean

I am so sorry, I am not familiar with git and I think the configuration on my local git is broken after my renaming, so I cannot put this commit directly in the last patch.
If you don't like this, I think I can cancel the last patch and create a new PR.

There is also a typo and use of deprecated function in intro.lean

---

.github/workflows/book.yml

Run CI on PRs that come from forks #107

---

.github/workflows/book.yml
CONTENTS.md
README.md

fix: broken link

---

lean/main/03_expressions.lean

Small addition to improve readability while reading the latest book.

added subsections to make it easier to eyeball content

---

lean/main/03_expressions.lean

As pointed out by Kayla Thomas [1], the paragraph on capture-avoiding substitution used an example that didn't actually demonstrate capture-avoiding substitution.
While I was at it, I also made the explanation a bit more explicit.
[1] https://leanprover.zulipchat.com/#narrow/stream/239415-metaprogramming-.2F-tactics/topic/.22Metaprogramming.20in.20Lean.204.22/near/473287822

03: fix explanation of capture-avoiding substitution

---

lean/extra/03_pretty-printing.lean

update pretty print section
* fix issue that delab for `#check foo` does not work
* Improve match expression patterns of Unexpander
see #72

update pretty print section

---

.github/workflows/book.yml
.github/workflows/ci.yml
.github/workflows/deploy.yml
lean/main/04_metam.lean

fix typos and update CI

---

lake-manifest.json
lean-toolchain
lean/main/01_intro.lean

update Lean version to `v4.17.0-rc1`

update Lean version

---

assets/blockPlay.js
book.toml

"Add a button to each code block to jump to the Lean 4 web."
