.github/workflows/book.yml, README.md, lean/cover.lean, md/cover.md, pygments/lean4.py
There are at least 2 ways to publish an artifact here -- one with [actions/upload-artifact](https://github.com/actions/upload-artifact), and the other what I've done in the PR -- with a release (one that continually self-updates). The advantage of the latter is that the PDF is immediately openable in a browser. See e.g. https://github.com/Julian/lean4-metaprogramming-book/releases/tag/latest. The disadvantage is that this means every time someone pulls, a `latest` tag will have been updated.
Obviously comments welcome if you prefer the other way.
As-is though, I set this to rebuild a PDF each time a PR or push to master is made.
=> Add a GitHub action to build LaTeX + a PDF on push

lean/main/cheat-sheet.lean, lean/main/elaboration.lean, lean/main/expressions.lean, lean/main/metam.lean
The book used to contain "metavariable", "meta variable" and
"meta-variable". We now consistenly use "metavariable", which is the
spelling used in Lean 4.
=> Unify spelling of "metavariable"

lean/main/macros.lean, lean/main/syntax.lean, md/main/macros.md, md/main/syntax.md
This addresses Patrick's comments from #39 regarding syntax and macros, in particular:
=> Address Patrick's comments regarding syntax and macros

.github/workflows/book.yml
* Don't run on PR (right now someone sending a PR overrides the released book, even before it's merged)
* Re-release each time, rather than just updating artifacts on a static release
* Run on Ubuntu runners in CI which are a bit faster
=> Tweak the PDF build a bit

lean/main/metam.lean, md/main/metam.md
See [this discussion](https://leanprover.zulipchat.com/#narrow/stream/239415-metaprogramming-.2F-tactics/topic/.E2.9C.94.20WHNF.20of.20partially.20applied.20constants) for an explanation of the corrections to the WHNF section.
=> `metam.lean`: minor fixes/clarifications

lean/main/metam.lean
Also some formatting fixes.
As discussed here: https://leanprover.zulipchat.com/#narrow/stream/239415-metaprogramming-.2F-tactics/topic/.E2.9C.94.20WHNF.20of.20partially.20applied.20constants
=> metam: fix wrong explanation of WHNF

README.md, lakefile.lean, lean-toolchain, lean/extra/options.lean, lean/extra/pretty-printing.lean, lean/main/dsls.lean, lean/main/elaboration.lean, lean/main/intro.lean, lean/main/macros.lean, lean/main/syntax.lean, md/extra/options.md, md/extra/pretty-printing.md, md/main/dsls.md, md/main/elaboration.md, md/main/intro.md, md/main/macros.md, md/main/syntax.md
The most notable change here is the explanation and usage of types syntax (`TSyntax`) there are two things left to do here:
- I did only explain the easy (although almost exclusive) case where `TSyntax` is only parameterized by one syntax category, in theory it can be parameterized by an entire list of syntax categories but that is rather rare
- I did not look through every bit of code from the other chapters to see whether we could add `TSyntax` there
=> Update to latest Lean

lean/main/metam.lean
`t <|> u` does not exist in Lean 4 at a tactic level. (It does exist as a monadic combinator.)
See https://leanprover-community.github.io/mathlib4_docs/Init/Tactics.html#Lean.Parser.Tactic.first
https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/tactic1.20.3C.7C.3E.20tactic2/near/289847287
=> fix: 't <|> u' -> 'first | t | u'

lakefile.lean, lean-toolchain, lean/extra/pretty-printing.lean, lean/main/cheat-sheet.lean, lean/main/dsls.lean, lean/main/elaboration.lean, lean/main/expressions.lean, lean/main/intro.lean, lean/main/metam.lean, md/extra/pretty-printing.md, md/main/cheat-sheet.md, md/main/dsls.md, md/main/elaboration.md, md/main/expressions.md, md/main/intro.md, md/main/metam.md
This PR ended up as a bit of a pile of stuff, but hopefully each point is uncontroversial.
* Update Lean to recent nightly.
* Avoid deprecated `MetaM` functions like `withMVarContext`.
* Avoid `mkConst` in favour of `Expr.const`, and the same for other `Expr` constructors.
* Use `isImplementationDetail` instead of `isAuxDecl`.
* Various improved formulations.
fixes #68
fixes #76
---
Btw I noticed that the deprecation linter didn't flag our use of deprecated functions. Any idea why this might be?
=> Clean up some deprecations etc.

.github/workflows/book.yml, lean/cover.lean, lean/extra/pretty-printing.lean, lean/main/expressions.lean, lean/main/metam.lean, lean/solutions/expressions.lean, lean/solutions/metam.lean, md/cover.md, md/extra/pretty-printing.md, md/main/expressions.md, md/main/metam.md, md/solutions/expressions.md, md/solutions/metam.md
>  **Explanation**: In previous PR I thought `.md` files will be automatically generated on push to master, they weren't, so pushing the final `.md` generation in this PR.
> From → to
>
> <img height="300" alt="image" src="https://user-images.githubusercontent.com/7578559/212422719-c581d34e-0251-4474-a5d7-375708b2f5d1.png"> <img height="300" alt="image" src="https://user-images.githubusercontent.com/7578559/212422682-29475d75-05db-43e0-81d1-a70b3ca00d9f.png">
> **Explanation**: like [Julian mentioned](https://github.com/arthurpaulino/lean4-metaprogramming-book/pull/32#issue-1261345911), there are 2 ways to generate a pdf - via **actions/upload-artifact** (makes it possible to download an artifact [from the artifacts section in actions tab] in a zip file; and then unzip it; and then see …
=> Enable pdf generation in prs; fix chapter structure

README.md, lean/main/elaboration.lean, lean/main/expressions.lean, lean/main/metam.lean, lean/main/syntax.lean, lean/solutions/elaboration.lean, lean/solutions/expressions.lean, lean/solutions/metam.lean, lean/solutions/syntax.lean, md/main/elaboration.md, md/main/expressions.md, md/main/metam.md, md/main/syntax.md, md/solutions/elaboration.md, md/solutions/expressions.md, md/solutions/metam.md, md/solutions/syntax.md
[Based on #84]
- Created exercises & solutions for **Ch.Syntax**
- Created exercises & solutions for **Ch.Elaboration**
- Fixed missing code blocks in **Ch.MetaM** exercises
- in `/solutions` we used to have abridged descriptions of the exercise text - removed that, let's just have the exercise number
- **Ch.Syntax** [Exercises](https://github.com/lakesare/lean4-metaprogramming-book/blob/lakesare_exercises_2/md/main/syntax.md#exercises), [Solutions](https://github.com/lakesare/lean4-metaprogramming-book/blob/lakesare_exercises_2/md/solutions/syntax.md)
- **Ch.Elaboration** [Exercises](https://github.com/lakesare/lean4-metaprogramming-book/blob/lakesare_exercises_2/md/main/elaboration.md#exercises), [Solutions](https://github.com/lakesare/lean4-metaprogramming-book/blob/lakesare_exercises_2 …
=> Exercises for Ch.Syntax & Ch.Elaboration

md/main/intro.md
1. There is no `symbol` constructor;
2. `Lean.Meta.intro1P` has been deprecated, use `Lean.MVarId.intro1P` .
=> There is a typo and use of deprecated function in `intro.md`

README.md, lean/main/intro.lean, lean/main/overview.lean, md/main/intro.md, md/main/overview.md
- Added a comment that we now have exercises & solutions for each chapter
- Added a paragraph on how python/ruby metaprogramming differs from what we mean by lean metaprogramming
- Moved **"Printing Messages"** and **"`partial` functions"** paragraphs to the new **Ch.Overview**
- A new chapter
- [**Ch.Introduction**](https://github.com/lakesare/lean4-metaprogramming-book/blob/lakesare_overview/md/main/intro.md)
- [**Ch.Overview**](https://github.com/lakesare/lean4-metaprogramming-book/blob/lakesare_overview/md/main/overview.md)
=> Add Ch.Overview

.github/workflows/book.yml
`apt update` was missing (and needed as package indices drift out of date).
=> Fix CI failing on package installation

lakefile.lean
* Remove `isLeanOnly` which is deprecated in newer Lean and will emit a warning
* Use `python3` not `python` as the executable we look for, as the latter is / should be a Py2 interpreter
=> Two minor lakefile tweaks

lean/main/intro.lean
`#assertType 5  : ?_` actually succeeds,
because the default type of `5` is `Nat`.
By changing the counterexample to
`#assertType [] : ?_` we get the expected failure.
closes #101
=> fix(intro): fix counterexample

lakefile.lean
Remove the `@[default_target]` attribute from the `lean4-metaprogramming-book` library. This prevents it from being automatically built on a `lake build`, which does not work because it just builds all the code in the book (incuding errors). This will help prevent [Reservoir](https://reservoir.lean-lang.org/) from giving the book a red cross.
Also uses the now-more-standard `where` syntax rather than braces for the configurations.
=> No default target in lakefile

lakefile.lean
Fixes a problem with `lake run build` not working on macOS and Unix.
see https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/mdbook.20setup.20template.20for.20Lean.20project
=> bug fix: invalid runCmd arguments

lean/main/03_expressions.lean
Universe level `levelOne` specified for Nat. Should be `levelZero`
----------
See [zulip discussion](https://leanprover.zulipchat.com/#narrow/stream/113489-new-members/topic/MetaEval.20failed.20to.20be.20synthesized.20for.20elaboration.20result/near/462965893)
=> Fixes universe levels in Chapter 03 "Expressions"

lean/main/04_metam.lean
In the following example in [Weak Head Normalisation](https://leanprover-community.github.io/lean4-metaprogramming-book/main/04_metam.html#weak-head-normalisation) section:
the expected output is:
```
#eval whnf' `(List.cons 1 [])
-- [1]
```
but the actual output is:
```
#eval whnf' `(List.cons 1 [])
-- @List.cons Nat 1 (@List.nil Nat)
```
This PR fixes the example code so that the actual output matches the one in the book.
=> Add `set_option pp.explicit false` in Weak Head Normal Form example

.github/workflows/book.yml
I got an email from GitHub saying v3 will be deprecated in December, so I figured I'd do this for repos under leanprover-community before I forgot.
=> upgrade to actions/upload-artifact@v4

lean/extra/01_options.lean
The implemention of `Option.get` is exactly what was written here.
=> chore: Use `Option.get` instead of `Options.get`
